### ISSUE TITLE
Mixing react and jquery for dom manipulation

### ISSUE THREAD

**Issue by MIJOTHY** [foundersandcoders/carrier-pigeon#113]
Mainly looking at collapsible.js, and potentially concise.js if that does DOM manipulation, but i don't know whether they're actually getting used so this might be a redundant issue. React has its own way of doing stuff and it wants to be all-encompassing. When using react, having state lying outside it is potentially not best practice (messes with the top-down data flow, more moving parts, could potentially cause conflicts in rendering). There are ways around it but it's generally easier to stick to one method for view rendering w/ React, finding plugins that do similar things but through manipulating the virtual DOM rather then directly manipulating the real DOM.

**Comment by NataliaLKB** [comment]
Neither are being used. But we definitely should remove them!

They were being used at one stage, and then we switched to react.

Will remove them in the next PR and created a seperate issue for this task: https://github.com/foundersandcoders/carrier-pigeon/issues/115

Really great issue! Thanks so much for this feedback.

**Comment by NataliaLKB** [comment]
@MIJOTHY did you see anywhere else where we made this mistake?

If not, please let me know if the PR that was merged can close this issue :)

**Comment by MIJOTHY** [comment]
Looks good.

**Comment by NataliaLKB** [comment]
@MIJOTHY thanks :)
