### ISSUE TITLE
Wrapping components in functions, passing them react & link

### ISSUE THREAD

**Issue by MIJOTHY** [foundersandcoders/carrier-pigeon#114]
What's the reasoning for this?

**Comment by NataliaLKB** [comment]
To prevent requiring React multiple times.

**Comment by MIJOTHY** [comment]
Browserify recursively trawls through your requires from the entry point and only bundles ones it hasn't seen before, so extra care isn't necessary. Requiring (e.g.) React in every file will still therefore only lead to one 'React' being bundled

**Comment by NataliaLKB** [comment]
Thanks so much for this. That is useful to know. 

Mostly we did it that way out of habit, as that was what we were used to.

But ultimately it was from the lack of React/Browserify knowledge. 

Really appreciate the feedback. Please let me know if the PR closes this issue

**Comment by MIJOTHY** [comment]
Yep looks good.
