### ISSUE TITLE
I don't know much about sql but...

### ISSUE THREAD

**Issue by MIJOTHY** [foundersandcoders/carrier-pigeon#125]
that's an awful lot of ['select().from().where().next()'...](https://github.com/foundersandcoders/carrier-pigeon/blob/master/server/lib/querys.js?ts=2#L41)

**Comment by NataliaLKB** [comment]
I agree! But I believe it is all needed, and potentially more!

This is so we can search a string through each column within the table regardless of whether it is a number, a date, or a string.

In this particular table, we have lots of columns (and the client is asking for even more!)

We also need to edit this to include even more as the same search functionality needs to search through more than one table in our database.

Though when we do this bit of further functionality we will likely rewire to make it a bit neater. @benjaminlees what do you think?

**Comment by benjaminlees** [comment]
lol completely agree the whole idea of the knew method chaining formate for the sql is that we can create some neat for loops as opposed to having loops which concatenate strings e.g "something" + var + "something"
So @MIJOTHY  your observation is a good one and i will set about cleaning them up today cheers.

**Comment by NataliaLKB** [comment]
@MIJOTHY [this](https://github.com/foundersandcoders/carrier-pigeon/blob/master/server/lib/querys.js?ts=2#L41) has been rewritten, is it better/more readable?

**Comment by MIJOTHY** [comment]
yeah nice 1 m8s
