### ISSUE TITLE
creds.json example file :)

### ISSUE THREAD

**Issue by Neats29** [foundersandcoders/carrier-pigeon#178]

**Comment by NataliaLKB** [comment]
Hello! Thanks @Neats29 :).

Question, do you mean have a creds.json example file in the README? 

Not sure if we want to do that because it is a commercial project, however it might be super useful if other people end up maintaining this project.

@benjaminlees what do you think?

**Comment by NataliaLKB** [comment]
@Neats29. Benji and I agreed that this would be useful. I put one in the README. Close this issue if you think this fixes the problem!

Thanks again :+1: .

**Comment by Neats29** [comment]
Sounds good! :)
