### ISSUE TITLE
Orders to be sorted by date created.

### ISSUE THREAD

**Issue by rug1** [foundersandcoders/carrier-pigeon#276]

**Comment by thegsi** [comment]
1) Date Range. Orders to be sorted by date created.
The order already seem to be sorted by date.

1. I just created a dummy, 16030682. I put the dates in the wrong order on purpose. When you print the BR (booking request) it sorts the dates in the correct order . But it does not sort in the correct  time order on the 14th (it goes 1400, 0900, 1300). 

On the other hand, order no. 15110446 shows the correct date order in the BR, but in the order overlay the orders got mixed up. It goes:
19.11
19.11
19.11
16.11
17.11
16.11

when entering the loading dates in the system, we always put the the earliest to load first

**Comment by rug1** [comment]
Linked to #284
