### ISSUE TITLE
Loading Order is mixed up

### ISSUE THREAD

**Issue by rug1** [foundersandcoders/carrier-pigeon#284]
See order 15100414, loading 3.11 showing 11am and then 9am. Apparently was rectified but seems not to be working again.
I think he wants these order by time but need to check.

**Comment by thegsi** [comment]
Five or six containers in one job contained loading in different days. But containers not in chronological order. First at the top.

**Comment by thegsi** [comment]
2) Loading order is mixed up. Do you want us to reorder chronologically? More recent to least?
2. yes please , chronologically, the first to load in the top of the list t to the last to load in the bottom

**Comment by rug1** [comment]
Can't find an example - need to ask Michael for example

**Comment by rug1** [comment]
Linked to #276
