### ISSUE TITLE
Create a more presentable booking request form

### ISSUE THREAD

**Issue by rug1** [foundersandcoders/carrier-pigeon#289]

**Comment by rug1** [comment]
[Coot-Freight-Booking-Request-template.pdf](https://github.com/foundersandcoders/carrier-pigeon/files/156919/Coot-Freight-Booking-Request-template.pdf)

**Comment by rug1** [comment]
[Coot-Freight-Booking-Request-template.pdf](https://github.com/foundersandcoders/carrier-pigeon/files/157004/Coot-Freight-Booking-Request-template.pdf)

**Comment by thegsi** [comment]
Chunky block of text on pdf. We need paragraph breaks.
Use other booking confirmation forms to design the form. 
Take the exisitig letterhead and pull more information from the system – difficult to move from html to pdf.

Problem having fixed sections of the page for the input of information. Zones to include text.
Possible to use multiple pages for the booking form.

Company name, contact details, address, legal sentences, information not taken from a particular job.
Letterhead included.

Simple design which is not cramped. But professional look is absolutely essential.

**Comment by thegsi** [comment]
[Michael_Templates.xlsx](https://github.com/foundersandcoders/carrier-pigeon/files/161491/Michael_Templates.xlsx)
