### ISSUE TITLE
Booking Request form needs to include the following...

### ISSUE THREAD

**Issue by rug1** [foundersandcoders/carrier-pigeon#290]
* Header - logo on the right hand side
 * date/job no/BR/coot freight (with standard spacing)
 * Address to be changed to registered office
 * One line headings to be renamed as follows:
     * date (collect on)
     * time load reference (collect at)

    ??? Removed Collection Ref.

     * type (unit type)
     * no of packages (could be shortened to "no of pkgs") 
     * gross weight (could be shortened to "weight" or "gross w")
     * commodity (make this column wider)
 * date format to be changed to xx/xx/xx
 * Change "Collect from" to "From" and change "Deliver to" to "To" (to be rearranged as 2 columns)
 * Change "Special instructions" to "Remarks"
 * Bullet point or paragraphs in "To", "From" and "Remarks" sections
 * collection details line (at the top) to be moved down slightly

***He mentions "kline" and "cldn br" - need to find out what this means!***

**Comment by thegsi** [comment]
1) Under the forms section what does kline/cldn BR mean?
1. K-line and CLDN are shipping lines. And here I refer to their booking confirmation/request forms as samples. I can forward them to you if you need. This is what I showed you in the meeting. BR= best regards

**Comment by thegsi** [comment]
We do need a ‘'collection reference’’.

**Comment by thegsi** [comment]
register office address  311 Winston House, 2 Dollis Park, London N3 1HF
