### ISSUE TITLE
Minor bugs questions for Michael

### ISSUE THREAD

**Issue by thegsi** [foundersandcoders/carrier-pigeon#293]

**Comment by thegsi** [comment]
Contacts - default view "reminder" in alphabetical order enhancement #279 -- (Alphabetical order based on company name) - (Do we want reminders at top as well?) 

Orders to be sorted by date created. #276   --- They are already sorted by date. Examples of when not?

Cannot delete no of packages when order is copied enhancement #285 -- seems fine?

Booking request print view - Date to be changed to 12.01.2016 (from 2016.12.01)  -- Where is 2016.12.01?

**Comment by thegsi** [comment]
We have not been able to replicate some of the minor bugs that you outlined on your email. 
If you can pass on screenshots or details of instances when they affected the system we would be grateful.

1) Date Range. Orders to be sorted by date created.
The order already seem to be sorted by date.

2) Reminders are ref when not due.
All the reminders in the system that are red have past their due date and ate thus labelled correctly. This makes it difficult for us to understand the cause of the issue.

3) Multiple reminders are created.
In the system, at present there is only a single reminder for each. No duplicates for these reminders exist. 

4) No packages cannot be deleted
We can delete on our system so we would be grateful for an explanation.

**Comment by rug1** [comment]
https://docs.google.com/document/d/1yVVc7j8sZ1hqqd_d8SS4_q6u7X-R3oEzxToKaAOdHog/edit?ts=56d72678
