### ISSUE TITLE
Application is down

### ISSUE THREAD

**Issue by emilyb7** [foundersandcoders/carrier-pigeon#319]
Hey all, Coot Freight's application down, which is an urgent problem for their business, and Dan has (randomly) put me on the case. He's given me a username and password for the AWS account but I'm not getting very far.

Can any of you who knows a bit more please get back to me? 

Sorry, I realise you all did this a long time ago and this is probably a bit annoying, but any help would be really appreciated.

**Comment by NataliaLKB** [comment]
@emilyb7 What is the problem more specifically?

**Comment by emilyb7** [comment]
@NataliaLKB no idea! Can I call / gitter you quickly to get a few details?

**Comment by thegsi** [comment]
@emilyb7 Just seen this let me know if there are still problems and I will try to help. I was in your position about 18 months ago!
